### ISSUE TITLE
Breaking the source breaks the watch task

### ISSUE THREAD

**Issue by jmeas** [jmeas/es6-library-boilerplate#12]
Thanks to @tbranyen for mentioning this.

If you make a change to the source file that cannot be compiled with browserify, the task breaks completely.

6to5 is what is breaking. The stack trace:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
SyntaxError: /Users/Jmeas/Webdev/es6-library-boilerplate/src/another.js: Unterminated string constant (9:11)
  7   | var Another = {
  8   |   anotherFn: function() {
> 9   |     return 'o
      |           ^
  10   |   }
  11   | };
  12   | 
    at raise (/Users/Jmeas/Webdev/es6-library-boilerplate/node_modules/gulp-6to5/node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:345:15)
    at readString (/Users/Jmeas/Webdev/es6-library-boilerplate/node_modules/gulp-6to5/node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:1162:11)
```

**Comment by jmeas** [comment]
Possible solutions:

1. Can I catch the error and prevent it from exploding the task?
2. Can [run-sequence](https://github.com/OverZealous/run-sequence) be used to prevent browserify from running if jshint fails?
